int fatorial(int n);
int fibonacci(int n);
int inverte(int n);
int inverteSig(int n);
int somaVetor(int vet[], int n);
int soma1aN(int n);
int potenciakn(int k, int n);
int maxDivCom(int a, int b);
int multRec(int a, int b);
int fatDuplo(int n);
int h(int m, int n);